Week7 Broken
I keep getting the following error messages in the console:
Unhandled Promise Rejection: TypeError: kingImage.addImage is not a function. (In 'kingImage.addImage(knightImage)', 'kingImage.addImage' is undefined)

After asking chatgpt, it suggested to replace p5.play v3 with v1.5 and attached this code for me to replace. When I do this though, I get these messages in the console:

[Error] Failed to load resource: the server responded with a status of 404 () (p5.play.min.js, line 0)
Refused to execute https://cdn.jsdelivr.net/npm/p5.play@1.5.0/lib/p5.play.min.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
ReferenceError: Can't find variable: createSprite